# Generated by Django 3.1.7 on 2021-06-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoFator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avaliacao', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Tipo de avaliação')),
                ('intensidade', models.IntegerField(verbose_name='Intensidade')),
                ('limite_tolerancia', models.IntegerField(null=True, verbose_name='Limite de tolerância')),
                ('tecnica_utilizada', models.CharField(max_length=1000, verbose_name='Técnica utilizada')),
                ('insalubridade', models.BooleanField(default=False, verbose_name='Insalubridade')),
                ('periculosidade', models.BooleanField(default=False, verbose_name='Periculosidade')),
                ('aposentadoria_especial', models.BooleanField(default=False, verbose_name='Aposentadoria especial')),
                ('utilizacao_epc', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Utilização de EPC')),
                ('epc_eficaz', models.BooleanField(default=False, verbose_name='EPC eficaz')),
                ('utilizacao_epi', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Utilização de EPI')),
                ('condicao_ambiental_fator_risco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.condicaoambientalfatorrisco')),
                ('fator_risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.fatorrisco', verbose_name='Fator de risco')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.unidademedida', verbose_name='Unidade de medida')),
            ],
        ),
        migrations.AddField(
            model_name='condicaoambientalfatorrisco',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='condicaoambientalfatorrisco',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='condicaoambientalfatorrisco',
            name='responsavel_registro_ambiental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.responsavelregistroambiental'),
        ),
        migrations.CreateModel(
            name='AnaliseEPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacao_epi', models.CharField(max_length=200, null=True, verbose_name='Certificação do EPI')),
                ('descricao_epi', models.CharField(max_length=1500, null=True, verbose_name='Descrição do EPI')),
                ('epi_eficaz', models.BooleanField(default=False, verbose_name='EPI eficaz')),
                ('hierarquia_medida_protecao_coletiva', models.BooleanField(default=False, verbose_name='Hierarquia das medidas de proteção coletiva')),
                ('observada_condicao_funcionamento', models.BooleanField(default=False, verbose_name='Observadas as condições de funcionamento')),
                ('observado_epi', models.BooleanField(default=False, verbose_name='Observada uso da EPI')),
                ('observado_prazo_validade_ca', models.BooleanField(default=False, verbose_name='Observada o prazo de validade do CA')),
                ('observado_periodicidade_troca', models.BooleanField(default=False, verbose_name='Observada a periodicidade de troca')),
                ('observada_higienizacao_epi', models.BooleanField(default=False, verbose_name='Observada higienização da EPI')),
                ('condicao_fator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.condicaofator')),
            ],
            options={
                'verbose_name': 'Análise de EPI',
                'verbose_name_plural': 'Análises de EPI',
            },
        )
    ]
