# Generated by Django 3.1.7 on 2021-05-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseepi',
            name='certificacao_epi',
            field=models.CharField(max_length=200, null=True, verbose_name='Certificação do EPI'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='descricao_epi',
            field=models.CharField(max_length=1500, null=True, verbose_name='Descrição do EPI'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='epi_eficaz',
            field=models.BooleanField(default=False, verbose_name='EPI eficaz'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='hierarquia_medida_protecao_coletiva',
            field=models.BooleanField(default=False, verbose_name='Hierarquia das medidas de proteção coletiva'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='observada_condicao_funcionamento',
            field=models.BooleanField(default=False, verbose_name='Observadas as condições de funcionamento'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='observada_higienizacao_epi',
            field=models.BooleanField(default=False, verbose_name='Observada higienização da EPI'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='observado_epi',
            field=models.BooleanField(default=False, verbose_name='Observada uso da EPI'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='observado_periodicidade_troca',
            field=models.BooleanField(default=False, verbose_name='Observada a periodicidade de troca'),
        ),
        migrations.AlterField(
            model_name='analiseepi',
            name='observado_prazo_validade_ca',
            field=models.BooleanField(default=False, verbose_name='Observada o prazo de validade do CA'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='codigo_cat',
            field=models.CharField(max_length=100, null=True, verbose_name='Código CAT'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='e_social_notificado',
            field=models.BooleanField(default=False, verbose_name='CAT informada ao E-SOCIAL'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='analises_epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicao_fator_risco', to='seguranca_trabalho.analiseepi', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='aposentadoria_especial',
            field=models.BooleanField(default=False, verbose_name='Aposentadoria especial'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='atividades',
            field=models.ManyToManyField(to='seguranca_trabalho.Atividade', verbose_name='Atividades'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='descricao_atividade_ambiente',
            field=models.CharField(max_length=1000, null=True, verbose_name='Descrição das atividades desempenhadas no trabalho'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='epc_eficaz',
            field=models.BooleanField(default=False, verbose_name='EPC eficaz'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='fator_risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.fatorrisco', verbose_name='Fator de risco'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='insalubridade',
            field=models.BooleanField(default=False, verbose_name='Insalubridade'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='intensidade',
            field=models.IntegerField(verbose_name='Intensidade'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='limite_tolerancia',
            field=models.IntegerField(null=True, verbose_name='Limite de tolerância'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='periculosidade',
            field=models.BooleanField(default=False, verbose_name='Periculosidade'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='tecnica_utilizada',
            field=models.CharField(max_length=1000, verbose_name='Técnica utilizada'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='tipo_avaliacao',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Tipo de avaliação'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.unidademedida', verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='utilizacao_epc',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Utilização de EPC'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='utilizacao_epi',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Utilização de EPI'),
        ),
        migrations.AlterField(
            model_name='medicoaso',
            name='cpf',
            field=models.CharField(max_length=13, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='medicoaso',
            name='nit',
            field=models.CharField(max_length=30, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='medicoaso',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='medicoaso',
            name='numero_inscricao',
            field=models.CharField(max_length=20, verbose_name='Número de inscrição'),
        ),
        migrations.AlterField(
            model_name='medicoaso',
            name='uf',
            field=models.CharField(max_length=10, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='coordenador_cpf',
            field=models.CharField(max_length=13, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='coordenador_crm',
            field=models.CharField(max_length=20, verbose_name='Número CRM'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='coordenador_nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='coordenador_uf',
            field=models.CharField(max_length=20, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='data_aso',
            field=models.DateTimeField(verbose_name='Data do ASO'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='data_exame',
            field=models.DateTimeField(verbose_name='Data do exame'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='estagiario',
            field=models.BooleanField(default=False, verbose_name='Estagiário'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='indicacao_resultado',
            field=models.IntegerField(verbose_name='Indicação do resultado'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='medicos',
            field=models.ManyToManyField(to='seguranca_trabalho.MedicoASO', verbose_name='Médico emitente do ASO'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='observacao_procedimento',
            field=models.CharField(max_length=1000, null=True, verbose_name='Observação do procedimento'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='ordem_exame',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Ordem do exame'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.procedimento', verbose_name='Procedimento'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='resultado_aso',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Resultado do ASO'),
        ),
        migrations.AlterField(
            model_name='monitoramentosaudetrabalhador',
            name='tipo_exame',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (9, 9)], verbose_name='Tipo de exame'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='cpf',
            field=models.CharField(max_length=13, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='nis',
            field=models.CharField(max_length=20, null=True, verbose_name='NIS'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='numero_inscricao',
            field=models.CharField(max_length=30, verbose_name='Número de inscrição'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='orgao_classe',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (9, 9)], verbose_name='Órgão de classe'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='sigla_orgao',
            field=models.CharField(max_length=20, null=True, verbose_name='Sigla do órgão (outros)'),
        ),
        migrations.AlterField(
            model_name='responsavelregistroambiental',
            name='uf',
            field=models.CharField(max_length=20, verbose_name='UF'),
        ),
    ]
