# Generated by Django 3.1.7 on 2021-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0003_auto_20210529_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicacaoacidentetrabalho',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='comunicacaoacidentetrabalho',
            name='tempo_hospital',
        ),
        migrations.AddField(
            model_name='comunicacaoacidentetrabalho',
            name='internacao',
            field=models.BooleanField(default=False, verbose_name='Internação'),
        ),
        migrations.AddField(
            model_name='comunicacaoacidentetrabalho',
            name='tempo_internacao',
            field=models.PositiveIntegerField(help_text='Tempo em dias', null=True, verbose_name='Tempo de hospitalização'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='acidente_data_hora',
            field=models.DateTimeField(verbose_name='Data/hora do acidente'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='acidente_data_obito',
            field=models.DateTimeField(null=True, verbose_name='Data/hora do óbito'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='acidente_endereco_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='acidente_horas_trabalhadas',
            field=models.PositiveIntegerField(verbose_name='Horas trabalhadas até o momento do acidente'),
        ),
        migrations.AlterField(
            model_name='comunicacaoacidentetrabalho',
            name='atestado_medico_data',
            field=models.DateTimeField(verbose_name='Data/hora do atestado médico'),
        ),
        migrations.AlterField(
            model_name='condicaofatorrisco',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='funcionarioequipamento',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
