# Generated by Django 3.1.7 on 2021-04-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0004_usuario_empresa_selecionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empresa_selecionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.empresa'),
        ),
    ]
