# Generated by Django 3.1.7 on 2021-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0005_auto_20210415_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoBrasileiraOcupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Classificação brasileira de ocupação',
                'verbose_name_plural': 'Classificações brasileira de ocupação',
            },
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cbo',
            field=models.CharField(help_text='Classificação brasileira de ocupação', max_length=50, null=True, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_erp',
            field=models.CharField(help_text='Código cadastrado nos sistemas de informação da empresa', max_length=100, verbose_name='Código ERP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_esocial',
            field=models.CharField(help_text='Código no E-SOCIAL', max_length=100, verbose_name='Código no E-SOCIAL'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=13, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_exame_admissional',
            field=models.DateTimeField(verbose_name='Data do exame admissional'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_exame_demissional',
            field=models.DateTimeField(help_text='Campo não obrigatório para funcionário ativo', null=True, verbose_name='Data do exame demissional'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nis',
            field=models.CharField(max_length=20, null=True, verbose_name='NIS'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nit',
            field=models.CharField(max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pasep',
            field=models.CharField(max_length=20, null=True, verbose_name='PASEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(max_length=20, null=True, verbose_name='PIS'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=15, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(max_length=50, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='url_imagem',
            field=models.CharField(max_length=1000, verbose_name='URL da imagem'),
        ),
    ]
