# Generated by Django 3.1.7 on 2021-06-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0005_auto_20210601_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        )
    ]
