# Generated by Django 3.1.7 on 2021-04-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0006_auto_20210416_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cbo',
            field=models.ForeignKey(help_text='Classificação brasileira de ocupação', null=True, on_delete=django.db.models.deletion.PROTECT, to='seguranca_trabalho.classificacaobrasileiraocupacao', verbose_name='CBO'),
        ),
    ]
